#!/bin/sh

if [ -f "$1" ] ; then
    case "$1" in
      *.tar.bz2)   tar xjvf "$1"  ;;
      *.tar.gz)    tar xzvf "$1"  ;;
      *.tar.xz)    tar xzvf "$1"  ;;
      *.bz2)       bunzip2 "$1"   ;;
      *.rar)       unrar x "$1"   ;;
      *.gz)        gunzip "$1"    ;;
      *.tar)       tar xf "$1"    ;;
      *.tbz2)      tar xjf "$1"   ;;
      *.tgz)       tar xzf "$1"   ;;
      *.xz)        xz -d "$1"     ;;
      *.zip)       unzip "$1"     ;;
      *.Z)         uncompress "$1";;
      *.7z)        7z x "$1"      ;;
      *.a)         ar x "$1"      ;;
      *.zst)       unzstd "$1"    ;;
      *)           echo "'$1' cannot be extracted via extract" ;;
    esac
else
    echo "'$1' is not a valid file"
fi
