#!/bin/sh
# Warning: this script is awful and might fail

d="[\"']"

#echo "$d"
sudo true

choice=$(sudo grep -i "^menuentry " /boot/grub/grub.cfg | awk -F"$d" '/.*/{print $2}' | grep "Windows" )

#echo "$choice"
#echo "$d$choice$d"

name=$(sudo grep -i "$d$choice$d" /boot/grub/grub.cfg | awk -F"$d" '{print $4}' )

echo "The chosen entry: $choice"
echo "The grub name: $name"

sudo grub-reboot "$name" && echo "Done" || echo "grub-reboot failed" && sudo reboot
